### ISSUE TITLE
vkAcquireNextImageKHR results in VkSuboptimalKhr

### ISSUE THREAD

**Issue by Qlii256** [realitix/vulkan#74]
I cannot render anything on screen because vkAcquireNextImageKHR keeps raising the exception VkSuboptimalKhr. I've read online that when this happens I can "ignore" it and continue on with the drawing of the frame. However, later on when submitting the image-index returned by vkAcquireNextImageKHR is None because it raised an expection.

pCommandBuffers=[self._command_buffers[image_index], ],

What can I do about this and why do I keep getting this error?

**Comment by realitix** [comment]
Hello @Qlii256,
Indeed if an exception is raised you can't get the image index (like you can see here: https://github.com/realitix/vulkan/blob/master/vulkan/_vulkan.py#L7170 )
Maybe adding a parameter to the function to bypass the exception raising.. Else you should fix this exception.

**Comment by alex-hildebrand** [comment]
I am reviving this issue, because I think it should not be marked as complete. 

Using the image index after getting VkSuboptimalKhr is a completely valid use case. Otherwise it is very complicatedly to recover from this state because the semaphore used in vkAcquireNextImageKHR stays signaled and can not be used again in the next vkAcquireNextImageKHR.

Can you please add a parameter to bypass the exception  for VkSuboptimalKhr?  That would be very helpful!
